// Code generated by BobGen psql v0.38.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models_test

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/stephenafamo/bob"
	"github.com/stephenafamo/bob/types"
	models "pg_partitioning/db/models"
)

// Set the testDB to enable tests that use the database
var testDB bob.Transactor

// Make sure the type Event runs hooks after queries
var _ bob.HookableType = &models.Event{}

// Make sure the type uuid.UUID satisfies database/sql.Scanner
var _ sql.Scanner = (*uuid.UUID)(nil)

// Make sure the type uuid.UUID satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(uuid.UUID)

// Make sure the type types.JSON[json.RawMessage] satisfies database/sql.Scanner
var _ sql.Scanner = (*types.JSON[json.RawMessage])(nil)

// Make sure the type types.JSON[json.RawMessage] satisfies database/sql/driver.Valuer
var _ driver.Valuer = *new(types.JSON[json.RawMessage])
