CREATE TABLE IF NOT EXISTS EVENTS(
    seq bigint GENERATED BY DEFAULT AS IDENTITY,
    uuid uuid NOT NULL,
    name varchar NOT NULL,
    actor_id uuid NOT NULL,
    aggregate_id uuid NOT NULL,

    payload jsonb NOT NULL,
    created_at timestamptz DEFAULT NOW() NOT NULL
) PARTITION BY range(created_at);
