// Code generated by BobGen psql v0.38.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import "context"

type Factory struct {
	baseEventMods EventModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewEvent(ctx context.Context, mods ...EventMod) *EventTemplate {
	o := &EventTemplate{f: f}

	if f != nil {
		f.baseEventMods.Apply(ctx, o)
	}

	EventModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) ClearBaseEventMods() {
	f.baseEventMods = nil
}

func (f *Factory) AddBaseEventMod(mods ...EventMod) {
	f.baseEventMods = append(f.baseEventMods, mods...)
}
